# EDA and Data PreProcessing

### from the problem statement figure out the type of learning it belongs to the reason is for the supervised learning we need to identify the input and output columns
# Rule that the dataset should follow
### 1. Feed only needed features
### 2. No missing values
### 3. There should not be any categorical values or string values
### 4. All the values should be on the same scale
### 5. Split your x and y into training and test set in case of supervised learning

In [2]:
# importing the libraries
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
# importing the dataset
df = pd.read_csv('D:/BJG Study Material/Resource Person/2020-21/rait/How Real Time Predictions are done with Machine Learning/programs/datasets/Data_preprocessing.csv')
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 280.0+ bytes


In [5]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [6]:
print(df['Age'].mean())

38.77777777777778


In [7]:
# extracting x and y from the dataset
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [8]:
# imputing the missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='median')
x[:,1:3] = imputer.fit_transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
# encoding the categorical values
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],
                       remainder='passthrough')
x = ct.fit_transform(x)
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [10]:
# encoding y
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [11]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
print(x)

[[ 1.22474487 -0.65465367 -0.65465367  0.76973439  0.77256767]
 [-0.81649658 -0.65465367  1.52752523 -1.69922498 -1.40879986]
 [-0.81649658  1.52752523 -0.65465367 -1.26352627 -0.86345798]
 [-0.81649658 -0.65465367  1.52752523 -0.10166303 -0.22722578]
 [-0.81649658  1.52752523 -0.65465367  0.18880278 -0.22722578]
 [ 1.22474487 -0.65465367 -0.65465367 -0.53736175 -0.49989673]
 [-0.81649658 -0.65465367  1.52752523 -0.10166303 -1.04523861]
 [ 1.22474487 -0.65465367 -0.65465367  1.35066601  1.40879986]
 [-0.81649658  1.52752523 -0.65465367  1.64113182  1.77236112]
 [ 1.22474487 -0.65465367 -0.65465367 -0.24689594  0.3181161 ]]


c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [12]:
from sklearn.model_selection import train_test_split
# the train test split function split x and y into training and test set
# by random shuffle pf the rows. to keep this random shuffle constant for all of
# us we use the random state parametere
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,
                                                random_state=0)
print(x_train)

[[ 1.22474487 -0.65465367 -0.65465367 -0.24689594  0.3181161 ]
 [-0.81649658 -0.65465367  1.52752523 -1.69922498 -1.40879986]
 [-0.81649658 -0.65465367  1.52752523 -0.10166303 -1.04523861]
 [ 1.22474487 -0.65465367 -0.65465367  1.35066601  1.40879986]
 [-0.81649658 -0.65465367  1.52752523 -0.10166303 -0.22722578]
 [ 1.22474487 -0.65465367 -0.65465367  0.76973439  0.77256767]
 [ 1.22474487 -0.65465367 -0.65465367 -0.53736175 -0.49989673]]
